"""
Build mapData.ts from Natural Earth public-domain sources.

- Africa countries: ne_50m_admin_0_countries (3 MB source) -> ~54 features, low detail
- Nigeria states:   ne_10m_admin_1_states_provinces (39 MB source) -> 37 features (36 states + FCT), simplified

Run once locally; commit mapData.ts. Re-run if sources change.
"""
import json
import os

HERE = os.path.dirname(__file__)
DATA = os.path.join(HERE, '_data')

with open(os.path.join(DATA, 'ne_countries.geojson'), encoding='utf-8') as f:
    countries = json.load(f)
with open(os.path.join(DATA, 'ne10_states.geojson'), encoding='utf-8') as f:
    states = json.load(f)

# --- Projection helpers ---
def project_africa(lon, lat):
    # Africa bbox: lon -20..55, lat -36..38 -> 1000x1000 canvas
    x = (lon - (-20)) / (55 - (-20)) * 1000
    y = (38 - lat) / (38 - (-36)) * 1000
    return x, y

def project_nigeria(lon, lat):
    # Nigeria bbox: lon 2.6..14.7, lat 4.2..13.9 -> 800x600
    x = (lon - 2.6) / (14.7 - 2.6) * 800
    y = (13.9 - lat) / (13.9 - 4.2) * 600
    return x, y

def simplify_ring(pts, min_step=0.5):
    """Distance-based simplification: keep a point if it is at least min_step pixels away from the last kept point."""
    if not pts:
        return pts
    out = [pts[0]]
    lx, ly = pts[0]
    for x, y in pts[1:-1]:
        if abs(x - lx) >= min_step or abs(y - ly) >= min_step:
            out.append((x, y))
            lx, ly = x, y
    # always close on the last point of the source ring (it'll equal the first because we Z below)
    if pts[-1] != out[-1]:
        out.append(pts[-1])
    return out

def coords_to_path(coordinates, project, min_step):
    parts = []
    def walk(rings):
        for ring in rings:
            if isinstance(ring[0][0], (list, tuple)):
                walk(ring)
            else:
                projected = [project(lon, lat) for lon, lat in ring]
                projected = [(round(x, 1), round(y, 1)) for x, y in projected]
                projected = simplify_ring(projected, min_step)
                if len(projected) < 3:
                    continue
                parts.append('M' + ' L'.join(f'{x},{y}' for x, y in projected) + 'Z')
    walk(coordinates)
    return ''.join(parts)

def shape_to_d(geom, project, min_step):
    t = geom['type']
    c = geom['coordinates']
    if t == 'Polygon':
        return coords_to_path([c], project, min_step)
    if t == 'MultiPolygon':
        return coords_to_path(c, project, min_step)
    raise ValueError(f'unsupported: {t}')

# --- Africa countries (low res, coarser simplification) ---
africa_paths = []
for feat in countries['features']:
    p = feat['properties']
    if p.get('CONTINENT') != 'Africa':
        continue
    iso = (p.get('ISO_A2_EH') or p.get('ISO_A2') or '').lower()
    if not iso or iso == '-99':
        iso = (p.get('ADM0_A3') or '')[:2].lower()
    name = p.get('NAME') or p.get('NAME_LONG') or p.get('SOVEREIGNT')
    if not iso:
        continue
    d = shape_to_d(feat['geometry'], project_africa, min_step=1.0)
    africa_paths.append({'iso': iso, 'name': name, 'd': d})
africa_paths.sort(key=lambda c: c['iso'])

# --- Nigeria states (finer simplification, since the map zooms in) ---
nigeria_paths = []
for feat in states['features']:
    p = feat['properties']
    if p.get('admin') != 'Nigeria' and p.get('iso_a2') != 'NG':
        continue
    name = p.get('name') or p.get('name_en')
    d = shape_to_d(feat['geometry'], project_nigeria, min_step=0.6)
    nigeria_paths.append({'name': name, 'd': d})
nigeria_paths.sort(key=lambda s: s['name'])

print(f'africa: {len(africa_paths)} features')
print(f'nigeria: {len(nigeria_paths)} features')

# --- Emit TypeScript ---
ts_out = os.path.join(HERE, 'mapData.ts')
total_chars = sum(len(c['d']) for c in africa_paths) + sum(len(s['d']) for s in nigeria_paths)
with open(ts_out, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by _build_svg.py from Natural Earth (public domain).\n')
    f.write('// Do not hand-edit. Re-run the script if sources change.\n')
    f.write(f'// Path-data character total: {total_chars} chars.\n\n')
    f.write('export interface CountryPath { iso: string; name: string; d: string; }\n')
    f.write('export interface StatePath   { name: string; d: string; }\n\n')

    f.write('export const AFRICA_COUNTRIES: CountryPath[] = [\n')
    for c in africa_paths:
        f.write(f"  {{ iso: {json.dumps(c['iso'])}, name: {json.dumps(c['name'])}, d: {json.dumps(c['d'])} }},\n")
    f.write('];\n\n')

    f.write('export const NIGERIA_STATES: StatePath[] = [\n')
    for s in nigeria_paths:
        f.write(f"  {{ name: {json.dumps(s['name'])}, d: {json.dumps(s['d'])} }},\n")
    f.write('];\n')

print(f'wrote {ts_out}, {total_chars} chars of path data total')
